{% set name = "nautilus-sampler" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nautilus-sampler-{{ version }}.tar.gz
  sha256: d4ac5226fd48a246605b7043b27716d6c90522549613920930ec9a1bedec1627

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - threadpoolctl

test:
  imports:
    - nautilus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/johannesulf/nautilus
  summary: Neural Network-Boosted Importance Sampling for Bayesian Statistics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johannesulf
