{% set name = "nautilus-sampler" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nautilus-sampler-{{ version }}.tar.gz
  sha256: 2fd57ae663a72b024d19f62a30c205abb038663098b92d852151c7cf9d5508dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - threadpoolctl

test:
  imports:
    - nautilus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/johannesulf/nautilus
  summary: Neural Network-Boosted Importance Sampling for Bayesian Statistics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johannesulf
