{% set name = "nautilus-sampler" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2b79b7145617930ca77c0b6d5cbe0aeac40bac56bfe921f3647c062dcf7a94b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - threadpoolctl

test:
  imports:
    - nautilus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/johannesulf/nautilus
  summary: Neural Network-Boosted Importance Sampling for Bayesian Statistics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johannesulf
