{% set name = "nautilus-sampler" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5dfafa344082d058b3fb0ad128216857f3c7fddb1d56adf8e3e6523ad6d95e97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - numpy >=1.18.0
    - scipy >=1.4.0
    - scikit-learn >=0.22.0
    - threadpoolctl >=3.0.0

test:
  imports:
    - nautilus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/johannesulf/nautilus
  summary: Neural Network-Boosted Importance Sampling for Bayesian Statistics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johannesulf
