{% set name = "nautilus-sampler" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 321374bcaf1f7ab2ebe98e1a8cbaee190da62453e34feafa8960cca5703650fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - threadpoolctl

test:
  imports:
    - nautilus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/johannesulf/nautilus
  summary: Neural Network-Boosted Importance Sampling for Bayesian Statistics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johannesulf
